/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captchas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCaptcha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captchas/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCaptcha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Returns fresh credentials. Clients must replace their stored refresh key with refreshKey from every successful response; the key may be rotated even when the current implementation returns the existing value. */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch: operations["patchAccount"];
        trace?: never;
    };
    "/v1/accounts/@batchGet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["batchGetAccounts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{accountId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete: operations["revokeSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "ACCESS_TOKEN_INVALID" | "ACCOUNT_IDENTIFIER_CONFLICT" | "ACCOUNT_NOT_FOUND" | "API_KEY_INVALID" | "BATCH_INVALID" | "CAPTCHA_CODE_INVALID" | "CAPTCHA_ID_INVALID" | "CAPTCHA_INVALID" | "CAPTCHA_RATE_LIMITED" | "EMAIL_INVALID" | "IDEMPOTENCY_CONFLICT" | "IDEMPOTENCY_IN_PROGRESS" | "LOGIN_IDENTIFIER_INVALID" | "LOGIN_INVALID" | "LOGIN_LOCKED" | "PAGE_INVALID" | "PASSWORD_INVALID" | "PATCH_INVALID" | "PHONE_INVALID" | "REFRESH_INVALID" | "REFRESH_KEY_INVALID" | "USERNAME_INVALID";
        LoginInput: {
            login: string;
            password: string;
            captchaId: string;
            /** @description Four characters from the case-insensitive captcha alphabet. */
            captchaCode: string;
        };
        RefreshInput: {
            refreshKey: string;
        };
        VerifyCaptchaInput: {
            id: string;
            /** @description Four characters from the case-insensitive captcha alphabet. */
            code: string;
        };
        CreateAccountInput: {
            username: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            password: string;
            active?: boolean;
            idempotencyKey?: string;
        };
        PatchAccountInput: {
            username?: string;
            phone?: string | null;
            /** Format: email */
            email?: string | null;
            active?: boolean;
        };
        BatchGetAccountsInput: {
            accountIds: string[];
        };
        ChangePasswordInput: {
            password: string;
        };
        AuthTokens: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            accountId: string;
            /** Format: date-time */
            refreshExpiresAt: string;
            /** @description Refresh key to persist for the next refresh. It may differ from the submitted key. */
            refreshKey: string;
            sessionId: string;
        };
        CaptchaVerification: {
            verified: boolean;
        };
        Session: {
            id: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Account: {
            id: string;
            username: string;
            phone: string | null;
            /** Format: email */
            email: string | null;
            active: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AccountCollection: {
            data: {
                /** @constant */
                type: "accounts";
                id: string;
                attributes: components["schemas"]["Account"];
            }[];
            links: {
                self: string;
                next?: string;
            };
            meta: {
                page: {
                    offset: number;
                    limit: number;
                    total: number;
                };
            };
        };
    };
    responses: {
        /** @description Captcha challenge */
        Captcha: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    id: string;
                    /** Format: uri */
                    imageDataUri: string;
                };
            };
        };
        /** @description Account */
        Account: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Account"];
            };
        };
        /** @description Access and refresh credentials */
        AuthTokens: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthTokens"];
            };
        };
        /** @description Captcha verification result */
        CaptchaVerification: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CaptchaVerification"];
            };
        };
        /** @description Active sessions */
        Sessions: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"][];
            };
        };
        /** @description JSON:API account collection */
        AccountCollection: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/vnd.api+json": components["schemas"]["AccountCollection"];
                "application/json": components["schemas"]["AccountCollection"];
            };
        };
        /** @description JSON response */
        Json: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": Record<string, never>;
            };
        };
        /** @description Stable error response: { code, message } */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    code: components["schemas"]["ErrorCode"];
                    message: string;
                };
            };
        };
        /** @description Dependency readiness failed */
        Unavailable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: {
        Login: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        Refresh: {
            content: {
                "application/json": components["schemas"]["RefreshInput"];
            };
        };
        VerifyCaptcha: {
            content: {
                "application/json": components["schemas"]["VerifyCaptchaInput"];
            };
        };
        CreateAccount: {
            content: {
                "application/json": components["schemas"]["CreateAccountInput"];
            };
        };
        PatchAccount: {
            content: {
                "application/json": components["schemas"]["PatchAccountInput"];
            };
        };
        BatchGetAccounts: {
            content: {
                "application/json": components["schemas"]["BatchGetAccountsInput"];
            };
        };
        ChangePassword: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Unavailable"];
        };
    };
    createCaptcha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Captcha"];
            429: components["responses"]["Error"];
        };
    };
    verifyCaptcha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["VerifyCaptcha"];
        responses: {
            200: components["responses"]["CaptchaVerification"];
            400: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Login"];
        responses: {
            200: components["responses"]["AuthTokens"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Refresh"];
        responses: {
            200: components["responses"]["AuthTokens"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description session removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    listAccounts: {
        parameters: {
            query?: {
                "page[offset]"?: number;
                "page[limit]"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AccountCollection"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CreateAccount"];
        responses: {
            201: components["responses"]["Account"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Account"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description account deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    patchAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PatchAccount"];
        responses: {
            200: components["responses"]["Account"];
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    batchGetAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["BatchGetAccounts"];
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ChangePassword"];
        responses: {
            /** @description password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Sessions"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    revokeSessions: {
        parameters: {
            query?: {
                sessionId?: string;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description sessions removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
}
