import { Region } from './entities/region.entity';

export const regionList: Region[] = [
  {
    code: 'AD',
    nameZh: '安道尔',
    nameEn: 'Andorra',
    dialingPrefix: '+376',
    namePinyin: 'an dao er',
  },
  {
    code: 'AE',
    nameZh: '阿联酋',
    nameEn: 'United Arab Emirates',
    dialingPrefix: '+971',
    namePinyin: 'a lian qiu',
  },
  {
    code: 'AF',
    nameZh: '阿富汗',
    nameEn: 'Afghanistan',
    dialingPrefix: '+93',
    namePinyin: 'a fu han',
  },
  {
    code: 'AG',
    nameZh: '安提瓜和巴布达',
    nameEn: 'Antigua and Barbuda',
    dialingPrefix: '+1268',
    namePinyin: 'an ti gua he ba bu da',
  },
  {
    code: 'AI',
    nameZh: '安圭拉',
    nameEn: 'Anguilla',
    dialingPrefix: '+1264',
    namePinyin: 'an gui la',
  },
  {
    code: 'AL',
    nameZh: '阿尔巴尼亚',
    nameEn: 'Albania',
    dialingPrefix: '+355',
    namePinyin: 'a er ba ni ya',
  },
  {
    code: 'AM',
    nameZh: '亚美尼亚',
    nameEn: 'Armenia',
    dialingPrefix: '+374',
    namePinyin: 'ya mei ni ya',
  },
  {
    code: 'AO',
    nameZh: '安哥拉',
    nameEn: 'Angola',
    dialingPrefix: '+244',
    namePinyin: 'an ge la',
  },
  {
    code: 'AQ',
    nameZh: '南极洲',
    nameEn: 'Antarctica',
    dialingPrefix: '+672',
    namePinyin: 'nan ji zhou',
  },
  {
    code: 'AR',
    nameZh: '阿根廷',
    nameEn: 'Argentina',
    dialingPrefix: '+54',
    namePinyin: 'a gen ting',
  },
  {
    code: 'AS',
    nameZh: '美属萨摩亚',
    nameEn: 'American Samoa',
    dialingPrefix: '+1684',
    namePinyin: 'mei shu sa mo ya',
  },
  {
    code: 'AT',
    nameZh: '奥地利',
    nameEn: 'Austria',
    dialingPrefix: '+43',
    namePinyin: 'ao di li',
  },
  {
    code: 'AU',
    nameZh: '澳大利亚',
    nameEn: 'Australia',
    dialingPrefix: '+61',
    namePinyin: 'ao da li ya',
  },
  {
    code: 'AW',
    nameZh: '阿鲁巴',
    nameEn: 'Aruba',
    dialingPrefix: '+297',
    namePinyin: 'a lu ba',
  },
  {
    code: 'AZ',
    nameZh: '阿塞拜疆',
    nameEn: 'Azerbaijan',
    dialingPrefix: '+994',
    namePinyin: 'a sai bai jiang',
  },
  {
    code: 'BA',
    nameZh: '波黑',
    nameEn: 'Bosnia and Herzegovina',
    dialingPrefix: '+387',
    namePinyin: 'bo hei',
  },
  {
    code: 'BB',
    nameZh: '巴巴多斯',
    nameEn: 'Barbados',
    dialingPrefix: '+1246',
    namePinyin: 'ba ba duo si',
  },
  {
    code: 'BD',
    nameZh: '孟加拉国',
    nameEn: 'Bangladesh',
    dialingPrefix: '+880',
    namePinyin: 'meng jia la guo',
  },
  {
    code: 'BE',
    nameZh: '比利时',
    nameEn: 'Belgium',
    dialingPrefix: '+32',
    namePinyin: 'bi li shi',
  },
  {
    code: 'BF',
    nameZh: '布基纳法索',
    nameEn: 'Burkina Faso',
    dialingPrefix: '+226',
    namePinyin: 'bu ji na fa suo',
  },
  {
    code: 'BG',
    nameZh: '保加利亚',
    nameEn: 'Bulgaria',
    dialingPrefix: '+359',
    namePinyin: 'bao jia li ya',
  },
  {
    code: 'BH',
    nameZh: '巴林',
    nameEn: 'Bahrain',
    dialingPrefix: '+973',
    namePinyin: 'ba lin',
  },
  {
    code: 'BI',
    nameZh: '布隆迪',
    nameEn: 'Burundi',
    dialingPrefix: '+257',
    namePinyin: 'bu long di',
  },
  {
    code: 'BJ',
    nameZh: '贝宁',
    nameEn: 'Benin',
    dialingPrefix: '+229',
    namePinyin: 'bei ning',
  },
  {
    code: 'BM',
    nameZh: '百慕大',
    nameEn: 'Bermuda',
    dialingPrefix: '+1441',
    namePinyin: 'bai mu da',
  },
  {
    code: 'BN',
    nameZh: '文莱',
    nameEn: 'Brunei',
    dialingPrefix: '+673',
    namePinyin: 'wen lai',
  },
  {
    code: 'BO',
    nameZh: '玻利维亚',
    nameEn: 'Bolivia',
    dialingPrefix: '+591',
    namePinyin: 'bo li wei ya',
  },
  {
    code: 'BR',
    nameZh: '巴西',
    nameEn: 'Brazil',
    dialingPrefix: '+55',
    namePinyin: 'ba xi',
  },
  {
    code: 'BS',
    nameZh: '巴哈马',
    nameEn: 'Bahamas',
    dialingPrefix: '+1242',
    namePinyin: 'ba ha ma',
  },
  {
    code: 'BT',
    nameZh: '不丹',
    nameEn: 'Bhutan',
    dialingPrefix: '+975',
    namePinyin: 'bu dan',
  },
  {
    code: 'BV',
    nameZh: '布韦岛',
    nameEn: 'Bouvet Island',
    dialingPrefix: '+55',
    namePinyin: 'bu wei dao',
  },
  {
    code: 'BW',
    nameZh: '博茨瓦纳',
    nameEn: 'Botswana',
    dialingPrefix: '+267',
    namePinyin: 'bo ci wa na',
  },
  {
    code: 'BY',
    nameZh: '白俄罗斯',
    nameEn: 'Belarus',
    dialingPrefix: '+375',
    namePinyin: 'bai e luo si',
  },
  {
    code: 'BZ',
    nameZh: '伯利兹',
    nameEn: 'Belize',
    dialingPrefix: '+501',
    namePinyin: 'bo li zi',
  },
  {
    code: 'CA',
    nameZh: '加拿大',
    nameEn: 'Canada',
    dialingPrefix: '+1',
    namePinyin: 'jia na da',
  },
  {
    code: 'CC',
    nameZh: '科科斯（基林）群岛',
    nameEn: 'Cocos (Keeling) Islands',
    dialingPrefix: '+61',
    namePinyin: 'ke ke si （ ji lin ） qun dao',
  },
  {
    code: 'CD',
    nameZh: '刚果（金）',
    nameEn: 'The Democratic Republic of Congo',
    dialingPrefix: '+243',
    namePinyin: 'gang guo （ jin ）',
  },
  {
    code: 'CF',
    nameZh: '中非',
    nameEn: 'Central African Republic',
    dialingPrefix: '+236',
    namePinyin: 'zhong fei',
  },
  {
    code: 'CG',
    nameZh: '刚果（布）',
    nameEn: 'Congo',
    dialingPrefix: '+242',
    namePinyin: 'gang guo （ bu ）',
  },
  {
    code: 'CH',
    nameZh: '瑞士',
    nameEn: 'Switzerland',
    dialingPrefix: '+41',
    namePinyin: 'rui shi',
  },
  {
    code: 'CI',
    nameZh: '科特迪瓦',
    nameEn: 'Ivory Coast',
    dialingPrefix: '+225',
    namePinyin: 'ke te di wa',
  },
  {
    code: 'CK',
    nameZh: '库克群岛',
    nameEn: 'Cook Islands',
    dialingPrefix: '+682',
    namePinyin: 'ku ke qun dao',
  },
  {
    code: 'CL',
    nameZh: '智利',
    nameEn: 'Chile',
    dialingPrefix: '+56',
    namePinyin: 'zhi li',
  },
  {
    code: 'CM',
    nameZh: '喀麦隆',
    nameEn: 'Cameroon',
    dialingPrefix: '+237',
    namePinyin: 'ka mai long',
  },
  {
    code: 'CN',
    nameZh: '中国',
    nameEn: 'China',
    dialingPrefix: '+86',
    namePinyin: 'zhong guo',
  },
  {
    code: 'CO',
    nameZh: '哥伦比亚',
    nameEn: 'Colombia',
    dialingPrefix: '+57',
    namePinyin: 'ge lun bi ya',
  },
  {
    code: 'CR',
    nameZh: '哥斯达黎加',
    nameEn: 'Costa Rica',
    dialingPrefix: '+506',
    namePinyin: 'ge si da li jia',
  },
  {
    code: 'CU',
    nameZh: '古巴',
    nameEn: 'Cuba',
    dialingPrefix: '+53',
    namePinyin: 'gu ba',
  },
  {
    code: 'CV',
    nameZh: '佛得角',
    nameEn: 'Cape Verde',
    dialingPrefix: '+238',
    namePinyin: 'fo de jiao',
  },
  {
    code: 'CX',
    nameZh: '圣诞岛',
    nameEn: 'Christmas Island',
    dialingPrefix: '+61',
    namePinyin: 'sheng dan dao',
  },
  {
    code: 'CY',
    nameZh: '塞浦路斯',
    nameEn: 'Cyprus',
    dialingPrefix: '+357',
    namePinyin: 'sai pu lu si',
  },
  {
    code: 'CZ',
    nameZh: '捷克',
    nameEn: 'Czech Republic',
    dialingPrefix: '+420',
    namePinyin: 'jie ke',
  },
  {
    code: 'DE',
    nameZh: '德国',
    nameEn: 'Germany',
    dialingPrefix: '+49',
    namePinyin: 'de guo',
  },
  {
    code: 'DJ',
    nameZh: '吉布提',
    nameEn: 'Djibouti',
    dialingPrefix: '+253',
    namePinyin: 'ji bu ti',
  },
  {
    code: 'DK',
    nameZh: '丹麦',
    nameEn: 'Denmark',
    dialingPrefix: '+45',
    namePinyin: 'dan mai',
  },
  {
    code: 'DM',
    nameZh: '多米尼克',
    nameEn: 'Dominica',
    dialingPrefix: '+1767',
    namePinyin: 'duo mi ni ke',
  },
  {
    code: 'DO',
    nameZh: '多米尼加',
    nameEn: 'Dominican Republic',
    dialingPrefix: '+1849',
    namePinyin: 'duo mi ni jia',
  },
  {
    code: 'DZ',
    nameZh: '阿尔及利亚',
    nameEn: 'Algeria',
    dialingPrefix: '+213',
    namePinyin: 'a er ji li ya',
  },
  {
    code: 'EC',
    nameZh: '厄瓜多尔',
    nameEn: 'Ecuador',
    dialingPrefix: '+593',
    namePinyin: 'e gua duo er',
  },
  {
    code: 'EE',
    nameZh: '爱沙尼亚',
    nameEn: 'Estonia',
    dialingPrefix: '+372',
    namePinyin: 'ai sha ni ya',
  },
  {
    code: 'EG',
    nameZh: '埃及',
    nameEn: 'Egypt',
    dialingPrefix: '+20',
    namePinyin: 'ai ji',
  },
  {
    code: 'EH',
    nameZh: '阿拉伯撒哈拉民主共和国',
    nameEn: 'Western Sahara',
    dialingPrefix: '+212',
    namePinyin: 'a la bo sa ha la min zhu gong he guo',
  },
  {
    code: 'ER',
    nameZh: '厄立特里亚',
    nameEn: 'Eritrea',
    dialingPrefix: '+291',
    namePinyin: 'e li te li ya',
  },
  {
    code: 'ES',
    nameZh: '西班牙',
    nameEn: 'Spain',
    dialingPrefix: '+34',
    namePinyin: 'xi ban ya',
  },
  {
    code: 'ET',
    nameZh: '埃塞俄比亚',
    nameEn: 'Ethiopia',
    dialingPrefix: '+251',
    namePinyin: 'ai sai e bi ya',
  },
  {
    code: 'FI',
    nameZh: '芬兰',
    nameEn: 'Finland',
    dialingPrefix: '+358',
    namePinyin: 'fen lan',
  },
  {
    code: 'FJ',
    nameZh: '斐济',
    nameEn: 'Fiji Islands',
    dialingPrefix: '+679',
    namePinyin: 'fei ji',
  },
  {
    code: 'FK',
    nameZh: '福克兰群岛',
    nameEn: 'Falkland Islands',
    dialingPrefix: '+500',
    namePinyin: 'fu ke lan qun dao',
  },
  {
    code: 'FM',
    nameZh: '密克罗尼西亚联邦',
    nameEn: 'Micronesia, Federated States of',
    dialingPrefix: '+691',
    namePinyin: 'mi ke luo ni xi ya lian bang',
  },
  {
    code: 'FO',
    nameZh: '法罗群岛',
    nameEn: 'Faroe Islands',
    dialingPrefix: '+298',
    namePinyin: 'fa luo qun dao',
  },
  {
    code: 'FR',
    nameZh: '法国',
    nameEn: 'France',
    dialingPrefix: '+33',
    namePinyin: 'fa guo',
  },
  {
    code: 'GA',
    nameZh: '加蓬',
    nameEn: 'Gabon',
    dialingPrefix: '+241',
    namePinyin: 'jia peng',
  },
  {
    code: 'GB',
    nameZh: '英国',
    nameEn: 'Northern Ireland',
    dialingPrefix: '+44',
    namePinyin: 'ying guo',
  },
  {
    code: 'GD',
    nameZh: '格林纳达',
    nameEn: 'Grenada',
    dialingPrefix: '+1473',
    namePinyin: 'ge lin na da',
  },
  {
    code: 'GE',
    nameZh: '格鲁吉亚',
    nameEn: 'Georgia',
    dialingPrefix: '+995',
    namePinyin: 'ge lu ji ya',
  },
  {
    code: 'GF',
    nameZh: '法属圭亚那',
    nameEn: 'French Guiana',
    dialingPrefix: '+594',
    namePinyin: 'fa shu gui ya na',
  },
  {
    code: 'GH',
    nameZh: '加纳',
    nameEn: 'Ghana',
    dialingPrefix: '+233',
    namePinyin: 'jia na',
  },
  {
    code: 'GI',
    nameZh: '直布罗陀',
    nameEn: 'Gibraltar',
    dialingPrefix: '+350',
    namePinyin: 'zhi bu luo tuo',
  },
  {
    code: 'GL',
    nameZh: '格陵兰',
    nameEn: 'Greenland',
    dialingPrefix: '+299',
    namePinyin: 'ge ling lan',
  },
  {
    code: 'GM',
    nameZh: '冈比亚',
    nameEn: 'Gambia',
    dialingPrefix: '+220',
    namePinyin: 'gang bi ya',
  },
  {
    code: 'GN',
    nameZh: '几内亚',
    nameEn: 'Guinea',
    dialingPrefix: '+224',
    namePinyin: 'ji nei ya',
  },
  {
    code: 'GP',
    nameZh: '瓜德罗普',
    nameEn: 'Guadeloupe',
    dialingPrefix: '+590',
    namePinyin: 'gua de luo pu',
  },
  {
    code: 'GQ',
    nameZh: '赤道几内亚',
    nameEn: 'Equatorial Guinea',
    dialingPrefix: '+240',
    namePinyin: 'chi dao ji nei ya',
  },
  {
    code: 'GR',
    nameZh: '希腊',
    nameEn: 'Greece',
    dialingPrefix: '+30',
    namePinyin: 'xi la',
  },
  {
    code: 'GS',
    nameZh: '南乔治亚和南桑威奇群岛',
    nameEn: 'South Georgia and the South Sandwich Islands',
    dialingPrefix: '+500',
    namePinyin: 'nan qiao zhi ya he nan sang wei qi qun dao',
  },
  {
    code: 'GT',
    nameZh: '危地马拉',
    nameEn: 'Guatemala',
    dialingPrefix: '+502',
    namePinyin: 'wei di ma la',
  },
  {
    code: 'GU',
    nameZh: '关岛',
    nameEn: 'Guam',
    dialingPrefix: '+1671',
    namePinyin: 'guan dao',
  },
  {
    code: 'GW',
    nameZh: '几内亚比绍',
    nameEn: 'Guinea-Bissau',
    dialingPrefix: '+245',
    namePinyin: 'ji nei ya bi shao',
  },
  {
    code: 'GY',
    nameZh: '圭亚那',
    nameEn: 'Guyana',
    dialingPrefix: '+592',
    namePinyin: 'gui ya na',
  },
  {
    code: 'HK',
    nameZh: '香港',
    nameEn: 'Hong Kong',
    dialingPrefix: '+852',
    namePinyin: 'xiang gang',
  },
  {
    code: 'HM',
    nameZh: '赫德岛和麦克唐纳群岛',
    nameEn: 'Heard Island and McDonald Islands',
    dialingPrefix: '+672',
    namePinyin: 'he de dao he mai ke tang na qun dao',
  },
  {
    code: 'HN',
    nameZh: '洪都拉斯',
    nameEn: 'Honduras',
    dialingPrefix: '+504',
    namePinyin: 'hong du la si',
  },
  {
    code: 'HR',
    nameZh: '克罗地亚',
    nameEn: 'Croatia',
    dialingPrefix: '+385',
    namePinyin: 'ke luo di ya',
  },
  {
    code: 'HT',
    nameZh: '海地',
    nameEn: 'Haiti',
    dialingPrefix: '+509',
    namePinyin: 'hai di',
  },
  {
    code: 'HU',
    nameZh: '匈牙利',
    nameEn: 'Hungary',
    dialingPrefix: '+36',
    namePinyin: 'xiong ya li',
  },
  {
    code: 'ID',
    nameZh: '印尼',
    nameEn: 'Indonesia',
    dialingPrefix: '+62',
    namePinyin: 'yin ni',
  },
  {
    code: 'IE',
    nameZh: '爱尔兰',
    nameEn: 'Ireland',
    dialingPrefix: '+353',
    namePinyin: 'ai er lan',
  },
  {
    code: 'IL',
    nameZh: '以色列',
    nameEn: 'Israel',
    dialingPrefix: '+972',
    namePinyin: 'yi se lie',
  },
  {
    code: 'IN',
    nameZh: '印度',
    nameEn: 'India',
    dialingPrefix: '+91',
    namePinyin: 'yin du',
  },
  {
    code: 'IO',
    nameZh: '英属印度洋领地',
    nameEn: 'British Indian Ocean Territory',
    dialingPrefix: '+246',
    namePinyin: 'ying shu yin du yang ling di',
  },
  {
    code: 'IQ',
    nameZh: '伊拉克',
    nameEn: 'Iraq',
    dialingPrefix: '+964',
    namePinyin: 'yi la ke',
  },
  {
    code: 'IR',
    nameZh: '伊朗',
    nameEn: 'Iran',
    dialingPrefix: '+98',
    namePinyin: 'yi lang',
  },
  {
    code: 'IS',
    nameZh: '冰岛',
    nameEn: 'Iceland',
    dialingPrefix: '+354',
    namePinyin: 'bing dao',
  },
  {
    code: 'IT',
    nameZh: '意大利',
    nameEn: 'Italy',
    dialingPrefix: '+39',
    namePinyin: 'yi da li',
  },
  {
    code: 'JM',
    nameZh: '牙买加',
    nameEn: 'Jamaica',
    dialingPrefix: '+1876',
    namePinyin: 'ya mai jia',
  },
  {
    code: 'JO',
    nameZh: '约旦',
    nameEn: 'Jordan',
    dialingPrefix: '+962',
    namePinyin: 'yue dan',
  },
  {
    code: 'JP',
    nameZh: '日本',
    nameEn: 'Japan',
    dialingPrefix: '+81',
    namePinyin: 'ri ben',
  },
  {
    code: 'KE',
    nameZh: '肯尼亚',
    nameEn: 'Kenya',
    dialingPrefix: '+254',
    namePinyin: 'ken ni ya',
  },
  {
    code: 'KG',
    nameZh: '吉尔吉斯斯坦',
    nameEn: 'Kyrgyzstan',
    dialingPrefix: '+996',
    namePinyin: 'ji er ji si si tan',
  },
  {
    code: 'KH',
    nameZh: '柬埔寨',
    nameEn: 'Cambodia',
    dialingPrefix: '+855',
    namePinyin: 'jian pu zhai',
  },
  {
    code: 'KI',
    nameZh: '基里巴斯',
    nameEn: 'Kiribati',
    dialingPrefix: '+686',
    namePinyin: 'ji li ba si',
  },
  {
    code: 'KM',
    nameZh: '科摩罗',
    nameEn: 'Comoros',
    dialingPrefix: '+269',
    namePinyin: 'ke mo luo',
  },
  {
    code: 'KN',
    nameZh: '圣基茨和尼维斯',
    nameEn: 'Saint Kitts and Nevis',
    dialingPrefix: '+1869',
    namePinyin: 'sheng ji ci he ni wei si',
  },
  {
    code: 'KP',
    nameZh: '朝鲜',
    nameEn: 'North Korea',
    dialingPrefix: '+850',
    namePinyin: 'zhao xian',
  },
  {
    code: 'KR',
    nameZh: '韩国',
    nameEn: 'South Korea',
    dialingPrefix: '+82',
    namePinyin: 'han guo',
  },
  {
    code: 'KW',
    nameZh: '科威特',
    nameEn: 'Kuwait',
    dialingPrefix: '+965',
    namePinyin: 'ke wei te',
  },
  {
    code: 'KY',
    nameZh: '开曼群岛',
    nameEn: 'Cayman Islands',
    dialingPrefix: '+1345',
    namePinyin: 'kai man qun dao',
  },
  {
    code: 'KZ',
    nameZh: '哈萨克斯坦',
    nameEn: 'Kazakhstan',
    dialingPrefix: '+7',
    namePinyin: 'ha sa ke si tan',
  },
  {
    code: 'LA',
    nameZh: '老挝',
    nameEn: 'Laos',
    dialingPrefix: '+856',
    namePinyin: 'lao zhua',
  },
  {
    code: 'LB',
    nameZh: '黎巴嫩',
    nameEn: 'Lebanon',
    dialingPrefix: '+961',
    namePinyin: 'li ba nen',
  },
  {
    code: 'LC',
    nameZh: '圣卢西亚',
    nameEn: 'Saint Lucia',
    dialingPrefix: '+1758',
    namePinyin: 'sheng lu xi ya',
  },
  {
    code: 'LI',
    nameZh: '列支敦士登',
    nameEn: 'Liechtenstein',
    dialingPrefix: '+423',
    namePinyin: 'lie zhi dun shi deng',
  },
  {
    code: 'LK',
    nameZh: '斯里兰卡',
    nameEn: 'Sri Lanka',
    dialingPrefix: '+94',
    namePinyin: 'si li lan ka',
  },
  {
    code: 'LR',
    nameZh: '利比里亚',
    nameEn: 'Liberia',
    dialingPrefix: '+231',
    namePinyin: 'li bi li ya',
  },
  {
    code: 'LS',
    nameZh: '莱索托',
    nameEn: 'Lesotho',
    dialingPrefix: '+266',
    namePinyin: 'lai suo tuo',
  },
  {
    code: 'LT',
    nameZh: '立陶宛',
    nameEn: 'Lithuania',
    dialingPrefix: '+370',
    namePinyin: 'li tao wan',
  },
  {
    code: 'LU',
    nameZh: '卢森堡',
    nameEn: 'Luxembourg',
    dialingPrefix: '+352',
    namePinyin: 'lu sen bao',
  },
  {
    code: 'LV',
    nameZh: '拉脱维亚',
    nameEn: 'Latvia',
    dialingPrefix: '+371',
    namePinyin: 'la tuo wei ya',
  },
  {
    code: 'LY',
    nameZh: '利比亚',
    nameEn: 'Libyan Arab Jamahiriya',
    dialingPrefix: '+218',
    namePinyin: 'li bi ya',
  },
  {
    code: 'MA',
    nameZh: '摩洛哥',
    nameEn: 'Morocco',
    dialingPrefix: '+212',
    namePinyin: 'mo luo ge',
  },
  {
    code: 'MC',
    nameZh: '摩纳哥',
    nameEn: 'Monaco',
    dialingPrefix: '+377',
    namePinyin: 'mo na ge',
  },
  {
    code: 'MD',
    nameZh: '摩尔多瓦',
    nameEn: 'Moldova',
    dialingPrefix: '+373',
    namePinyin: 'mo er duo wa',
  },
  {
    code: 'MG',
    nameZh: '马达加斯加',
    nameEn: 'Madagascar',
    dialingPrefix: '+261',
    namePinyin: 'ma da jia si jia',
  },
  {
    code: 'MH',
    nameZh: '马绍尔群岛',
    nameEn: 'Marshall Islands',
    dialingPrefix: '+692',
    namePinyin: 'ma shao er qun dao',
  },
  {
    code: 'MK',
    nameZh: '北马其顿',
    nameEn: 'North Macedonia',
    dialingPrefix: '+389',
    namePinyin: 'bei ma qi dun',
  },
  {
    code: 'ML',
    nameZh: '马里',
    nameEn: 'Mali',
    dialingPrefix: '+223',
    namePinyin: 'ma li',
  },
  {
    code: 'MM',
    nameZh: '缅甸',
    nameEn: 'Myanmar',
    dialingPrefix: '+95',
    namePinyin: 'mian dian',
  },
  {
    code: 'MN',
    nameZh: '蒙古',
    nameEn: 'Mongolia',
    dialingPrefix: '+976',
    namePinyin: 'meng gu',
  },
  {
    code: 'MO',
    nameZh: '澳门',
    nameEn: 'Macao',
    dialingPrefix: '+853',
    namePinyin: 'ao men',
  },
  {
    code: 'MP',
    nameZh: '北马里亚纳群岛',
    nameEn: 'Northern Mariana Islands',
    dialingPrefix: '+1670',
    namePinyin: 'bei ma li ya na qun dao',
  },
  {
    code: 'MQ',
    nameZh: '马提尼克',
    nameEn: 'Martinique',
    dialingPrefix: '+596',
    namePinyin: 'ma ti ni ke',
  },
  {
    code: 'MR',
    nameZh: '毛里塔尼亚',
    nameEn: 'Mauritania',
    dialingPrefix: '+222',
    namePinyin: 'mao li ta ni ya',
  },
  {
    code: 'MS',
    nameZh: '蒙特塞拉特',
    nameEn: 'Montserrat',
    dialingPrefix: '+1664',
    namePinyin: 'meng te sai la te',
  },
  {
    code: 'MT',
    nameZh: '马耳他',
    nameEn: 'Malta',
    dialingPrefix: '+356',
    namePinyin: 'ma er ta',
  },
  {
    code: 'MU',
    nameZh: '毛里求斯',
    nameEn: 'Mauritius',
    dialingPrefix: '+230',
    namePinyin: 'mao li qiu si',
  },
  {
    code: 'MV',
    nameZh: '马尔代夫',
    nameEn: 'Maldives',
    dialingPrefix: '+960',
    namePinyin: 'ma er dai fu',
  },
  {
    code: 'MW',
    nameZh: '马拉维',
    nameEn: 'Malawi',
    dialingPrefix: '+265',
    namePinyin: 'ma la wei',
  },
  {
    code: 'MX',
    nameZh: '墨西哥',
    nameEn: 'Mexico',
    dialingPrefix: '+52',
    namePinyin: 'mo xi ge',
  },
  {
    code: 'MY',
    nameZh: '马来西亚',
    nameEn: 'Malaysia',
    dialingPrefix: '+60',
    namePinyin: 'ma lai xi ya',
  },
  {
    code: 'MZ',
    nameZh: '莫桑比克',
    nameEn: 'Mozambique',
    dialingPrefix: '+258',
    namePinyin: 'mo sang bi ke',
  },
  {
    code: 'NA',
    nameZh: '纳米比亚',
    nameEn: 'Namibia',
    dialingPrefix: '+264',
    namePinyin: 'na mi bi ya',
  },
  {
    code: 'NC',
    nameZh: '新喀里多尼亚',
    nameEn: 'New Caledonia',
    dialingPrefix: '+687',
    namePinyin: 'xin ka li duo ni ya',
  },
  {
    code: 'NE',
    nameZh: '尼日尔',
    nameEn: 'Niger',
    dialingPrefix: '+227',
    namePinyin: 'ni ri er',
  },
  {
    code: 'NF',
    nameZh: '诺福克岛',
    nameEn: 'Norfolk Island',
    dialingPrefix: '+672',
    namePinyin: 'nuo fu ke dao',
  },
  {
    code: 'NG',
    nameZh: '尼日利亚',
    nameEn: 'Nigeria',
    dialingPrefix: '+234',
    namePinyin: 'ni ri li ya',
  },
  {
    code: 'NI',
    nameZh: '尼加拉瓜',
    nameEn: 'Nicaragua',
    dialingPrefix: '+505',
    namePinyin: 'ni jia la gua',
  },
  {
    code: 'NL',
    nameZh: '荷兰',
    nameEn: 'Netherlands',
    dialingPrefix: '+31',
    namePinyin: 'he lan',
  },
  {
    code: 'NO',
    nameZh: '挪威',
    nameEn: 'Norway',
    dialingPrefix: '+47',
    namePinyin: 'nuo wei',
  },
  {
    code: 'NP',
    nameZh: '尼泊尔',
    nameEn: 'Nepal',
    dialingPrefix: '+977',
    namePinyin: 'ni bo er',
  },
  {
    code: 'NR',
    nameZh: '瑙鲁',
    nameEn: 'Nauru',
    dialingPrefix: '+674',
    namePinyin: 'nao lu',
  },
  {
    code: 'NU',
    nameZh: '纽埃',
    nameEn: 'Niue',
    dialingPrefix: '+683',
    namePinyin: 'niu ai',
  },
  {
    code: 'NZ',
    nameZh: '新西兰',
    nameEn: 'New Zealand',
    dialingPrefix: '+64',
    namePinyin: 'xin xi lan',
  },
  {
    code: 'OM',
    nameZh: '阿曼',
    nameEn: 'Oman',
    dialingPrefix: '+968',
    namePinyin: 'a man',
  },
  {
    code: 'PA',
    nameZh: '巴拿马',
    nameEn: 'Panama',
    dialingPrefix: '+507',
    namePinyin: 'ba na ma',
  },
  {
    code: 'PE',
    nameZh: '秘鲁',
    nameEn: 'Peru',
    dialingPrefix: '+51',
    namePinyin: 'mi lu',
  },
  {
    code: 'PF',
    nameZh: '法属波利尼西亚',
    nameEn: 'French Polynesia',
    dialingPrefix: '+689',
    namePinyin: 'fa shu bo li ni xi ya',
  },
  {
    code: 'PG',
    nameZh: '巴布亚新几内亚',
    nameEn: 'Papua New Guinea',
    dialingPrefix: '+675',
    namePinyin: 'ba bu ya xin ji nei ya',
  },
  {
    code: 'PH',
    nameZh: '菲律宾',
    nameEn: 'Philippines',
    dialingPrefix: '+63',
    namePinyin: 'fei lv bin',
  },
  {
    code: 'PK',
    nameZh: '巴基斯坦',
    nameEn: 'Pakistan',
    dialingPrefix: '+92',
    namePinyin: 'ba ji si tan',
  },
  {
    code: 'PL',
    nameZh: '波兰',
    nameEn: 'Poland',
    dialingPrefix: '+48',
    namePinyin: 'bo lan',
  },
  {
    code: 'PM',
    nameZh: '圣皮埃尔和密克隆',
    nameEn: 'Saint Pierre and Miquelon',
    dialingPrefix: '+508',
    namePinyin: 'sheng pi ai er he mi ke long',
  },
  {
    code: 'PN',
    nameZh: '皮特凯恩群岛',
    nameEn: 'Pitcairn',
    dialingPrefix: '+64',
    namePinyin: 'pi te kai en qun dao',
  },
  {
    code: 'PR',
    nameZh: '波多黎各',
    nameEn: 'Puerto Rico',
    dialingPrefix: '+1939',
    namePinyin: 'bo duo li ge',
  },
  {
    code: 'PS',
    nameZh: '巴勒斯坦',
    nameEn: 'Palestine',
    dialingPrefix: '+970',
    namePinyin: 'ba le si tan',
  },
  {
    code: 'PT',
    nameZh: '葡萄牙',
    nameEn: 'Portugal',
    dialingPrefix: '+351',
    namePinyin: 'pu tao ya',
  },
  {
    code: 'PW',
    nameZh: '帕劳',
    nameEn: 'Palau',
    dialingPrefix: '+680',
    namePinyin: 'pa lao',
  },
  {
    code: 'PY',
    nameZh: '巴拉圭',
    nameEn: 'Paraguay',
    dialingPrefix: '+595',
    namePinyin: 'ba la gui',
  },
  {
    code: 'QA',
    nameZh: '卡塔尔',
    nameEn: 'Qatar',
    dialingPrefix: '+974',
    namePinyin: 'ka ta er',
  },
  {
    code: 'RE',
    nameZh: '留尼汪',
    nameEn: 'Reunion',
    dialingPrefix: '+262',
    namePinyin: 'liu ni wang',
  },
  {
    code: 'RO',
    nameZh: '罗马尼亚',
    nameEn: 'Romania',
    dialingPrefix: '+40',
    namePinyin: 'luo ma ni ya',
  },
  {
    code: 'RS',
    nameZh: '塞尔维亚',
    nameEn: 'Serbia',
    dialingPrefix: '+381',
    namePinyin: 'sai er wei ya',
  },
  {
    code: 'RU',
    nameZh: '俄罗斯',
    nameEn: 'Russia',
    dialingPrefix: '+7',
    namePinyin: 'e luo si',
  },
  {
    code: 'RW',
    nameZh: '卢旺达',
    nameEn: 'Rwanda',
    dialingPrefix: '+250',
    namePinyin: 'lu wang da',
  },
  {
    code: 'SA',
    nameZh: '沙特阿拉伯',
    nameEn: 'Saudi Arabia',
    dialingPrefix: '+966',
    namePinyin: 'sha te a la bo',
  },
  {
    code: 'SB',
    nameZh: '所罗门群岛',
    nameEn: 'Solomon Islands',
    dialingPrefix: '+677',
    namePinyin: 'suo luo men qun dao',
  },
  {
    code: 'SC',
    nameZh: '塞舌尔',
    nameEn: 'Seychelles',
    dialingPrefix: '+248',
    namePinyin: 'sai she er',
  },
  {
    code: 'SD',
    nameZh: '苏丹',
    nameEn: 'Sudan',
    dialingPrefix: '+249',
    namePinyin: 'su dan',
  },
  {
    code: 'SE',
    nameZh: '瑞典',
    nameEn: 'Sweden',
    dialingPrefix: '+46',
    namePinyin: 'rui dian',
  },
  {
    code: 'SG',
    nameZh: '新加坡',
    nameEn: 'Singapore',
    dialingPrefix: '+65',
    namePinyin: 'xin jia po',
  },
  {
    code: 'SH',
    nameZh: '圣赫勒拿、阿森松和特里斯坦-达库尼亚',
    nameEn: 'Saint Helena',
    dialingPrefix: '+290',
    namePinyin: 'sheng he le na 、 a sen song he te li si tan - da ku ni ya',
  },
  {
    code: 'SI',
    nameZh: '斯洛文尼亚',
    nameEn: 'Slovenia',
    dialingPrefix: '+386',
    namePinyin: 'si luo wen ni ya',
  },
  {
    code: 'SJ',
    nameZh: '斯瓦尔巴和扬马延',
    nameEn: 'Svalbard and Jan Mayen',
    dialingPrefix: '+47',
    namePinyin: 'si wa er ba he yang ma yan',
  },
  {
    code: 'SK',
    nameZh: '斯洛伐克',
    nameEn: 'Slovakia',
    dialingPrefix: '+421',
    namePinyin: 'si luo fa ke',
  },
  {
    code: 'SL',
    nameZh: '塞拉利昂',
    nameEn: 'Sierra Leone',
    dialingPrefix: '+232',
    namePinyin: 'sai la li ang',
  },
  {
    code: 'SM',
    nameZh: '圣马力诺',
    nameEn: 'San Marino',
    dialingPrefix: '+378',
    namePinyin: 'sheng ma li nuo',
  },
  {
    code: 'SN',
    nameZh: '塞内加尔',
    nameEn: 'Senegal',
    dialingPrefix: '+221',
    namePinyin: 'sai nei jia er',
  },
  {
    code: 'SO',
    nameZh: '索马里',
    nameEn: 'Somalia',
    dialingPrefix: '+252',
    namePinyin: 'suo ma li',
  },
  {
    code: 'SR',
    nameZh: '苏里南',
    nameEn: 'Suriname',
    dialingPrefix: '+597',
    namePinyin: 'su li nan',
  },
  {
    code: 'SS',
    nameZh: '南苏丹',
    nameEn: 'South Sudan',
    dialingPrefix: '+211',
    namePinyin: 'nan su dan',
  },
  {
    code: 'ST',
    nameZh: '圣多美和普林西比',
    nameEn: 'Sao Tome and Principe',
    dialingPrefix: '+239',
    namePinyin: 'sheng duo mei he pu lin xi bi',
  },
  {
    code: 'SV',
    nameZh: '萨尔瓦多',
    nameEn: 'El Salvador',
    dialingPrefix: '+503',
    namePinyin: 'sa er wa duo',
  },
  {
    code: 'SY',
    nameZh: '叙利亚',
    nameEn: 'Syria',
    dialingPrefix: '+963',
    namePinyin: 'xu li ya',
  },
  {
    code: 'SZ',
    nameZh: '斯威士兰',
    nameEn: 'Swaziland',
    dialingPrefix: '+268',
    namePinyin: 'si wei shi lan',
  },
  {
    code: 'TC',
    nameZh: '特克斯和凯科斯群岛',
    nameEn: 'Turks and Caicos Islands',
    dialingPrefix: '+1649',
    namePinyin: 'te ke si he kai ke si qun dao',
  },
  {
    code: 'TD',
    nameZh: '乍得',
    nameEn: 'Chad',
    dialingPrefix: '+235',
    namePinyin: 'zha de',
  },
  {
    code: 'TF',
    nameZh: '法属南部领地',
    nameEn: 'French Southern territories',
    dialingPrefix: '+262',
    namePinyin: 'fa shu nan bu ling di',
  },
  {
    code: 'TG',
    nameZh: '多哥',
    nameEn: 'Togo',
    dialingPrefix: '+228',
    namePinyin: 'duo ge',
  },
  {
    code: 'TH',
    nameZh: '泰国',
    nameEn: 'Thailand',
    dialingPrefix: '+66',
    namePinyin: 'tai guo',
  },
  {
    code: 'TJ',
    nameZh: '塔吉克斯坦',
    nameEn: 'Tajikistan',
    dialingPrefix: '+992',
    namePinyin: 'ta ji ke si tan',
  },
  {
    code: 'TK',
    nameZh: '托克劳',
    nameEn: 'Tokelau',
    dialingPrefix: '+690',
    namePinyin: 'tuo ke lao',
  },
  {
    code: 'TM',
    nameZh: '土库曼斯坦',
    nameEn: 'Turkmenistan',
    dialingPrefix: '+993',
    namePinyin: 'tu ku man si tan',
  },
  {
    code: 'TN',
    nameZh: '突尼斯',
    nameEn: 'Tunisia',
    dialingPrefix: '+216',
    namePinyin: 'tu ni si',
  },
  {
    code: 'TO',
    nameZh: '汤加',
    nameEn: 'Tonga',
    dialingPrefix: '+676',
    namePinyin: 'tang jia',
  },
  {
    code: 'TR',
    nameZh: '土耳其',
    nameEn: 'Turkey',
    dialingPrefix: '+90',
    namePinyin: 'tu er qi',
  },
  {
    code: 'TT',
    nameZh: '特立尼达和多巴哥',
    nameEn: 'Trinidad and Tobago',
    dialingPrefix: '+1868',
    namePinyin: 'te li ni da he duo ba ge',
  },
  {
    code: 'TV',
    nameZh: '图瓦卢',
    nameEn: 'Tuvalu',
    dialingPrefix: '+688',
    namePinyin: 'tu wa lu',
  },
  {
    code: 'TZ',
    nameZh: '坦桑尼亚',
    nameEn: 'Tanzania',
    dialingPrefix: '+255',
    namePinyin: 'tan sang ni ya',
  },
  {
    code: 'UA',
    nameZh: '乌克兰',
    nameEn: 'Ukraine',
    dialingPrefix: '+380',
    namePinyin: 'wu ke lan',
  },
  {
    code: 'UG',
    nameZh: '乌干达',
    nameEn: 'Uganda',
    dialingPrefix: '+256',
    namePinyin: 'wu gan da',
  },
  {
    code: 'UM',
    nameZh: '美国本土外小岛屿',
    nameEn: 'United States Minor Outlying Islands',
    dialingPrefix: '+1',
    namePinyin: 'mei guo ben tu wai xiao dao yu',
  },
  {
    code: 'US',
    nameZh: '美国',
    nameEn: 'United States',
    dialingPrefix: '+1',
    namePinyin: 'mei guo',
  },
  {
    code: 'UY',
    nameZh: '乌拉圭',
    nameEn: 'Uruguay',
    dialingPrefix: '+598',
    namePinyin: 'wu la gui',
  },
  {
    code: 'UZ',
    nameZh: '乌兹别克斯坦',
    nameEn: 'Uzbekistan',
    dialingPrefix: '+998',
    namePinyin: 'wu zi bie ke si tan',
  },
  {
    code: 'VA',
    nameZh: '梵蒂冈',
    nameEn: 'Holy See (Vatican City State)',
    dialingPrefix: '+379',
    namePinyin: 'fan di gang',
  },
  {
    code: 'VC',
    nameZh: '圣文森特和格林纳丁斯',
    nameEn: 'Saint Vincent and the Grenadines',
    dialingPrefix: '+1784',
    namePinyin: 'sheng wen sen te he ge lin na ding si',
  },
  {
    code: 'VE',
    nameZh: '委内瑞拉',
    nameEn: 'Venezuela',
    dialingPrefix: '+58',
    namePinyin: 'wei nei rui la',
  },
  {
    code: 'VG',
    nameZh: '英属维尔京群岛',
    nameEn: 'Virgin Islands, British',
    dialingPrefix: '+1',
    namePinyin: 'ying shu wei er jing qun dao',
  },
  {
    code: 'VI',
    nameZh: '美属维尔京群岛',
    nameEn: 'Virgin Islands, U.S.',
    dialingPrefix: '+1',
    namePinyin: 'mei shu wei er jing qun dao',
  },
  {
    code: 'VN',
    nameZh: '越南',
    nameEn: 'Vietnam',
    dialingPrefix: '+84',
    namePinyin: 'yue nan',
  },
  {
    code: 'VU',
    nameZh: '瓦努阿图',
    nameEn: 'Vanuatu',
    dialingPrefix: '+678',
    namePinyin: 'wa nu a tu',
  },
  {
    code: 'WF',
    nameZh: '瓦利斯和富图纳',
    nameEn: 'Wallis and Futuna',
    dialingPrefix: '+681',
    namePinyin: 'wa li si he fu tu na',
  },
  {
    code: 'WS',
    nameZh: '萨摩亚',
    nameEn: 'Samoa',
    dialingPrefix: '+685',
    namePinyin: 'sa mo ya',
  },
  {
    code: 'YE',
    nameZh: '也门',
    nameEn: 'Yemen',
    dialingPrefix: '+967',
    namePinyin: 'ye men',
  },
  {
    code: 'YT',
    nameZh: '马约特',
    nameEn: 'Mayotte',
    dialingPrefix: '+262',
    namePinyin: 'ma yue te',
  },
  {
    code: 'ZA',
    nameZh: '南非',
    nameEn: 'South Africa',
    dialingPrefix: '+27',
    namePinyin: 'nan fei',
  },
  {
    code: 'ZM',
    nameZh: '赞比亚',
    nameEn: 'Zambia',
    dialingPrefix: '+260',
    namePinyin: 'zan bi ya',
  },
  {
    code: 'ZW',
    nameZh: '津巴布韦',
    nameEn: 'Zimbabwe',
    dialingPrefix: '+263',
    namePinyin: 'jin ba bu wei',
  },
];
