{{- if .Values.playground.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stargate-next.playgroundServiceName" . }}-secret
  labels:
    {{- include "stargate-next.labels" . | nindent 4 }}
    app.kubernetes.io/component: playground
type: Opaque
stringData:
  STARGATE_API_KEY: {{ .Values.stargateNext.secrets.stargateApiKey | quote }}
  STARGATE_JWT_SECRET: {{ .Values.stargateNext.secrets.stargateJwtSecret | quote }}
  {{- if .Values.playground.config.stargateJwtPublicKey }}
  STARGATE_JWT_PUBLIC_KEY: {{ .Values.playground.config.stargateJwtPublicKey | quote }}
  {{- end }}
{{- end }}
